sitechina/china/urls.py
from django.contrib.auth.decorators import login_required
from django.template.defaulttags import url
from django.urls import path, register_converter

from china import views, converters

from china.views import ChinaCategory

register_converter(converters.FourDigitYearConverter, "year4")

urlpatterns = [

    #path('cats/<slug:cat_slug>/', views.categories_by_slug, name='cats'),
    #path('cats/<int:cat_id>/', views.categories, name='cats_id'),

    path('find/', views.find_information, name='find'),
    path('about/', views.about, name='about'),
    path('add/', views.AddPage.as_view(), name='add_page'),
    path('', views.ChinaHome.as_view(), name='home'),
    path('category/<slug:cat_slug>/', ChinaCategory.as_view(), name='category'),
    path('tag/<slug:tag_slug>/', views.TagPostList.as_view(), name='tag'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    path('edit/<slug:slug>/', views.UpdatePage.as_view(), name='edit_page'),
    path('delete/<slug:slug>/', views.DeletePost.as_view(), name='delete'),



    #path('add/', views.addpage, name='add_page'),

    #path('post/<slug:post_slug>/', views.show_post,  name='post'),

    #path('category/<slug:cat_slug>/', views.show_category, name='category'),
    #path('tag/<slug:tag_slug>/', views.show_tag_postlist, name='tag'),

   # path('process_add/', views.process_add, name='process_add'),
]

sitechina/sitechina/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path
from china import views
from sitechina import settings

# from django.views.defaults import page_not_found
handler404 = views.page_not_found

# from django.views.defaults import page_not_found
handler404 = views.page_not_found
admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Информационный сайт о Китае"
# register_converter(converters.FourDigitYearConverter, "year4")
urlpatterns = [
    path('admin/', admin.site.urls),
    path('china/', include('china.urls')),
    path('users/', include('users.urls', namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

sitechina/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from sitechina import settings
from . import views

app_name = "users"
urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logoutUser, name='logout'),

    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

    path('password-reset/', PasswordResetView.as_view(
        template_name="users/password_reset_form.html",
        email_template_name="users/password_reset_email.html",
        success_url=reverse_lazy("users:password_reset_done")
    ),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                          success_url=reverse_lazy("users:password_reset_complete")
                                          ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),
   ]

sitechina/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    photo = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True, null=True, verbose_name="Фотография")
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name="Дата рождения")
# Create your models here.

sitechina/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
import datetime

from sitechina import settings


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={'class': 'forminput'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'forminput'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'forminput'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name',
                  'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class':
                                                'form-input'}),
            'first_name':
                forms.TextInput(attrs={'class': 'form-input'}),
            'last_name':
                forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='Email', widget=forms.TextInput(attrs={'class': 'forminput'}))
    this_year = datetime.date.today().year
    date_birth = forms.DateField(widget=forms.SelectDateWidget(years=tuple(range(this_year - 100, this_year - 5))))
    extra_context = {'title': "Профиль пользователя", 'default_image': settings.DEFAULT_USER_IMAGE}

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email',
                  'date_birth', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name':
                forms.TextInput(attrs={'class': 'form-input'}),
            'last_name':
                forms.TextInput(attrs={'class': 'form-input'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput(attrs={'class': 'forminput'}))

sitechina/users/views.py
from django.contrib.auth import authenticate, logout, login, get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetCompleteView
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from sitechina import settings
from users.forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUser(LoginView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'
    extra_context = {'title': "Авторизация"}


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': "Регистрация"}
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': "Профиль пользователя",
                     'default_image': settings.DEFAULT_USER_IMAGE}
    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('users:profile')


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"
    extra_context = {'title': "Изменение пароля"}


def logoutUser(request):
    next_url = request.POST.get('next', 'home')
    logout(request)
    return redirect(reverse(next_url))


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = "users/password_reset_complete.html"
    success_url = reverse_lazy("users:password_reset_complete")

sitechina/users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Авторизация</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p>
        <p ><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
        <input type="hidden" name="next" value="{{ next }}">
        <button type="submit">Войти</button>
    </p>
</form>
{% endblock %}

sitechina/users/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block content %}
<h1>Пароль успешно изменен!</h1>
<p>Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

sitechina/users/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block content %}
<h1>Изменение пароля</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}
    </div>
    {% for f in form %}
    <p><label class="form-label" for="{{f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p>
        <button type="submit">Изменить пароль
        </button>
    </p>
</form>
{% endblock %}

sitechina/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block content %}
<h1>Пароль изменен</h1>
<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для <a href="{% url 'users:login' %}">входа в систему</a>.</p>
{% endblock %}

sitechina/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block content %}
<h1>Новый пароль</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}
    </div>
    {% for f in form %}
    <p><label class="form-label" for="{{f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p>
        <button type="submit">Сохранить</button>
    </p>
</form>
{% endblock %}

sitechina/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<h1>Сброс пароля</h1>
<p>Мы отправили вам по электронной почте инструкции по
    установка пароля, если существует учетная запись с
    адрес электронной почты, который вы ввели. Вы должны получить их в ближайшее время</p>
<p>Если вы не получили электронное письмо, пожалуйста,
    убедитесь, что вы ввели адрес, который вы зарегистрировали
    с и проверьте папку со спамом.</p>
{% endblock %}

sitechina/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

sitechina/users/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block content %}
<h1>Восстановление пароля</h1>
<form method="post">
    {% csrf_token %}
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label}}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p>
        <button type="submit">Сбросить по Email</button>
    </p>
</form>
{% endblock %}

sitechina/users/templates/users/profile.html
{% extends 'base.html' %}
{% block content %}
<h1>Профиль</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if user.photo %}
    <p><img src="{{ user.photo.url }}">
        {% else %}
    <p ><img src="{{ default_image }}">
        {% endif %}

    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <hr>
    <p><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
    <p>
        <button type="submit">Сохранить</button>
    </p>
</form>
{% endblock %}

sitechina/users/templates/users/register.html
{% extends 'base.html' %}
{% block content %}
<h1>Регистрация</h1>
<form method="post">
 {% csrf_token %}
 <input type="hidden" name="next" value="{{ next }}"/>
 <div class="form-error">{{ form.non_field_errors }}</div>
 {% for f in form %}
 <p ><label class="form-label" for="{{f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
 <div class="form-error">{{ f.errors }}</div>
 {% endfor %}
 <p ><button type="submit">Регистрация</button></p>
</form>
{% endblock %}

sitechina/users/templates/users/register_done.html
{% extends 'base.html' %}
{% block content %}
<h1>Добро пожаловать!</h1>
<p>Вы успешно зарегистрировались на сайте! Для входа в
    систему необходимо авторизоваться по этой <a href="{%url 'users:login' %}">ссылке</a>
</p>
{% endblock %}